# Comment that will be sent if an issue is judged to be closed
comment: "Your issue has been closed, as it did not follow our issue template. Please follow it :)"
issueConfigs:
- content:
# bug report
  - "Issue Description"
  - "Modpack version"
  - "Logs"
- content:
# feature request
  - "Is your feature request related to a problem? Please describe"
  - "Describe the solution you'd like"
  - "Additional context"
 - content:
# development
  - "Notes"
  - "Additional context"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: true
# The issue is judged to be legal if it includes all keywords from any of these three configs.
# Or it will be closed by the app.
